sudo: required
services:
    - docker

before_install:
    - docker build -t phawit9/docer-react -f Dockerfile.dev .

script:
    - docker run -e CI=true phawit9/docer-react npm run test -- --coverage